/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projeto.view;


import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;

/**
 *
 * @author rodri
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public String usuarioLogado;
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon= new ImageIcon(getClass().getResource("/images/fundo.jpg"));
        Image image = icon.getImage();
        painel_desktop = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image, 0 ,0 , getWidth(),getHeight(),this);
            }
        };
        jPanel1 = new javax.swing.JPanel();
        lblusario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu1 = new javax.swing.JMenu();
        MenuCliente = new javax.swing.JMenuItem();
        Menu2 = new javax.swing.JMenu();
        MenuFuncionario = new javax.swing.JMenuItem();
        Menu3 = new javax.swing.JMenu();
        MenuFornecedor = new javax.swing.JMenuItem();
        Menu4 = new javax.swing.JMenu();
        MenuControledeEstoque = new javax.swing.JMenuItem();
        MenuConsultaProdutos = new javax.swing.JMenuItem();
        Menu5 = new javax.swing.JMenu();
        MenuPDV = new javax.swing.JMenuItem();
        menu_posicao = new javax.swing.JMenuItem();
        menu_controVenda = new javax.swing.JMenuItem();
        Menu6 = new javax.swing.JMenu();
        MenuTrocarUsuario = new javax.swing.JMenuItem();
        MenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Controle de estoque");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lblusario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblusario.setForeground(new java.awt.Color(51, 153, 255));
        lblusario.setText("Usuario");

        jLabel2.setText("Usuário logado :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(lblusario)
                .addContainerGap(697, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel2)
                    .addContainerGap(763, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblusario)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(9, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addContainerGap()))
        );

        painel_desktop.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painel_desktopLayout = new javax.swing.GroupLayout(painel_desktop);
        painel_desktop.setLayout(painel_desktopLayout);
        painel_desktopLayout.setHorizontalGroup(
            painel_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painel_desktopLayout.setVerticalGroup(
            painel_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_desktopLayout.createSequentialGroup()
                .addGap(0, 370, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Menu1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Menu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clientes.png"))); // NOI18N
        Menu1.setText("Clientes");

        MenuCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        MenuCliente.setText("Controle de Clientes");
        MenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuClienteActionPerformed(evt);
            }
        });
        Menu1.add(MenuCliente);

        jMenuBar1.add(Menu1);

        Menu2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Menu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/funcionarios.png"))); // NOI18N
        Menu2.setText("Funcionários");

        MenuFuncionario.setText("Controle de funcionarios");
        MenuFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFuncionarioActionPerformed(evt);
            }
        });
        Menu2.add(MenuFuncionario);

        jMenuBar1.add(Menu2);

        Menu3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Menu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fornecedores.png"))); // NOI18N
        Menu3.setText("Fornecedores");

        MenuFornecedor.setText("Controle de fonecedores");
        MenuFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFornecedorActionPerformed(evt);
            }
        });
        Menu3.add(MenuFornecedor);

        jMenuBar1.add(Menu3);

        Menu4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Menu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/produtos.png"))); // NOI18N
        Menu4.setText("Produtos");

        MenuControledeEstoque.setText("Controle de estoque");
        MenuControledeEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuControledeEstoqueActionPerformed(evt);
            }
        });
        Menu4.add(MenuControledeEstoque);

        MenuConsultaProdutos.setText("Consulta de Produtos");
        MenuConsultaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuConsultaProdutosActionPerformed(evt);
            }
        });
        Menu4.add(MenuConsultaProdutos);

        jMenuBar1.add(Menu4);

        Menu5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Menu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vendas.png"))); // NOI18N
        Menu5.setText("Vendas");

        MenuPDV.setText("Abrir PDV");
        MenuPDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPDVActionPerformed(evt);
            }
        });
        Menu5.add(MenuPDV);

        menu_posicao.setText("Posição do dia");
        menu_posicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_posicaoActionPerformed(evt);
            }
        });
        Menu5.add(menu_posicao);

        menu_controVenda.setText("Controle de Vendas");
        menu_controVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_controVendaActionPerformed(evt);
            }
        });
        Menu5.add(menu_controVenda);

        jMenuBar1.add(Menu5);

        Menu6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Menu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/configuracoes.png"))); // NOI18N
        Menu6.setText("Configurações");

        MenuTrocarUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        MenuTrocarUsuario.setText("Trocar Usuario");
        MenuTrocarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuTrocarUsuarioActionPerformed(evt);
            }
        });
        Menu6.add(MenuTrocarUsuario);

        jMenuBar1.add(Menu6);

        MenuSair.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sair.png"))); // NOI18N
        MenuSair.setText("Sair");
        MenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel_desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_desktop)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        lblusario.setText(usuarioLogado);
    }//GEN-LAST:event_formWindowActivated

    private void MenuTrocarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuTrocarUsuarioActionPerformed
        // Efetuar logOut
        FmrLogin telaLogin = new FmrLogin();
        this.dispose();
        telaLogin.setVisible(true);
    }//GEN-LAST:event_MenuTrocarUsuarioActionPerformed

    private void MenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuSairMouseClicked
        //Sair do programa
        Object[] options = { "Confirmar", "Cancelar" }; 
        int op=JOptionPane.showConfirmDialog(null, "Deseja realmente sair?","Atenção",YES_NO_OPTION);
        if(op==0){
            System.exit(0);
        }
    }//GEN-LAST:event_MenuSairMouseClicked

    private void MenuConsultaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuConsultaProdutosActionPerformed
        // Menu consulta de produtos
        FrmProdutos tela= new FrmProdutos();
        tela.jTabbedPane1.setSelectedIndex(1);//abrir a aba 1 que é a de consulta produtos
        tela.setVisible(true);
    }//GEN-LAST:event_MenuConsultaProdutosActionPerformed

    private void MenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuClienteActionPerformed
        //abrindo tela de clientes
        FrmCliente tela= new FrmCliente();
        
        tela.setVisible(true);
    }//GEN-LAST:event_MenuClienteActionPerformed

    private void MenuFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFuncionarioActionPerformed
        //abrindo tela de Funcionarios 
        FrmFuncionarios tela= new FrmFuncionarios();
        tela.setVisible(true);
    }//GEN-LAST:event_MenuFuncionarioActionPerformed

    private void MenuFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFornecedorActionPerformed
        //abrindo tela de Fornecedores 
        FrmFornecedor tela= new FrmFornecedor();
        tela.setVisible(true);
    }//GEN-LAST:event_MenuFornecedorActionPerformed

    private void MenuPDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPDVActionPerformed
        //abrindo tela de vendas 
        FrmVendas tela= new FrmVendas();
        tela.setVisible(true);
    }//GEN-LAST:event_MenuPDVActionPerformed

    private void menu_posicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_posicaoActionPerformed
        //abrindo tela de totalVendas 
        FmrTotalVenda tela= new FmrTotalVenda();
        tela.setVisible(true);
    }//GEN-LAST:event_menu_posicaoActionPerformed

    private void menu_controVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_controVendaActionPerformed
        //abrindo tela de historico de vendas 
        FmrHistorico tela= new FmrHistorico();
        tela.setVisible(true);
    }//GEN-LAST:event_menu_controVendaActionPerformed

    private void MenuControledeEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuControledeEstoqueActionPerformed
        //abrindo tela de historico de vendas 
        FmrEstoque tela= new FmrEstoque();
        tela.setVisible(true);
    }//GEN-LAST:event_MenuControledeEstoqueActionPerformed

 

    @Override
    public void setExtendedState(int state) {
        super.setExtendedState(state); //To change body of generated methods, choose Tools | Templates.
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu1;
    private javax.swing.JMenu Menu2;
    private javax.swing.JMenu Menu3;
    private javax.swing.JMenu Menu4;
    private javax.swing.JMenu Menu5;
    private javax.swing.JMenu Menu6;
    private javax.swing.JMenuItem MenuCliente;
    private javax.swing.JMenuItem MenuConsultaProdutos;
    private javax.swing.JMenuItem MenuControledeEstoque;
    private javax.swing.JMenuItem MenuFornecedor;
    public javax.swing.JMenuItem MenuFuncionario;
    private javax.swing.JMenuItem MenuPDV;
    private javax.swing.JMenu MenuSair;
    private javax.swing.JMenuItem MenuTrocarUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblusario;
    public javax.swing.JMenuItem menu_controVenda;
    public javax.swing.JMenuItem menu_posicao;
    private javax.swing.JDesktopPane painel_desktop;
    // End of variables declaration//GEN-END:variables
}
